POST /upload HTTP/1.1
Host: localhost:9090
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryQB5eoMMQtmtBWlgn
Content-Length: 138

------WebKitFormBoundaryQB5eoMMQtmtBWlgn
Content-Disposition: form-data; name="field1"

value1
------WebKitFormBoundaryQB5eoMMQtmtBWlgn
Content-Disposition: form-data; name="file1"; filename="example.txt"
Content-Type: text/plain

(content of the file)
------WebKitFormBoundaryQB5eoMMQtmtBWlgn--
